default:
  target: dev
  outputs:
    dev:
      type: redshift
      host: redshift-cluster-2.cmwaeomvtjzi.us-east-2.redshift.amazonaws.com
      user: awsuser
      password: Dynamics238
      port: 5439
      dbname: dev
      schema: analytics
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      # search_path: public # optional, not recommended
#      sslmode: [optional, set the sslmode used to connect to the database (in case this parameter is set, will look for ca in ~/.postgresql/root.crt)]

